//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudenParent
    {
        public int StudentID { get; set; }
        public string St_name { get; set; }
        public string St_address { get; set; }
        public Nullable<System.DateTime> St_birthday { get; set; }
        public string Pa_name { get; set; }
        public string Pa_sex { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
